### ISSUE TITLE
Milestone planning: Complete range of functions

### ISSUE THREAD

**Issue by samtrion** [dailydevops/healthchecks#31]
Collective ticket for the overview of the targeted scope of functions.

The focus here is always on the provision of easily configurable health checks via 'IConfiguration' or dependency injection. Hardcoded values are avoided as far as possible.

- [ ] NetEvolve.HealthChecks
- NetEvolve.HealthChecks.Azure.* - [Supported service types](https://www.nuget.org/packages?q=Azure.ResourceManager.)
  - [ ] NetEvolve.HealthChecks.Azure.ApplicationInsights
  - [ ] NetEvolve.HealthChecks.Azure.Blob
  - [ ] NetEvolve.HealthChecks.Azure.CosmosDB
  - [ ] NetEvolve.HealthChecks.Azure.DigitalTwin
  - [ ] NetEvolve.HealthChecks.Azure.Files
  - [ ] NetEvolve.HealthChecks.Azure.IotHub
  - [ ] NetEvolve.HealthChecks.Azure.KeyVault
  - [ ] NetEvolve.HealthChecks.Azure.Queue
  - [ ] NetEvolve.HealthChecks.Azure.ServiceBus
  - [ ] NetEvolve.HealthChecks.Azure.Synapse
  - [ ] NetEvolve.HealthChecks.Azure.Table
- [ ] NetEvolve.HealthChecks.LiteDB
- [ ] NetEvolve.HealthChecks.MySql
- [ ] NetEvolve.HealthChecks.MySql.Connector
- [ ] NetEvolve.HealthChecks.Npgsql
- [ ] NetEvolve.HealthChecks.Oracle
- [ ] NetEvolve.HealthChecks.SQLite
- [ ] NetEvolve.HealthChecks.SqlServer
- [ ] NetEvolve.HealthChecks.SqlServer.Legacy
